version: v41.0.3
files:
  - .github/workflows/security-analysis.yaml
  - .github/workflows/renovate_dependency_management.yaml
values:
  renovateCronjobSchedule: "48 7 * * 1-5" # This is UTC -> At 08:48 CET / 09:48 CEST on every day-of-week from Monday through Friday.
